### ISSUE TITLE
怎么配置debug的时候带上项目名称

### ISSUE THREAD

**Issue by marvinma** [caspar-chen/swagger-ui-layer#1]
比如我打开网址：http://localhost:8080/project/docs.html.
里面有个mapper是persons。
如果直接在浏览器访问http://localhost:8080/project/persons，就能够得到结果。
但是在ui里点击这个接口的debug就404，因为发出的url是http://localhost:8080/persons。怎么解决

**Comment by caspar-chen** [comment]
你用的是springmvc吗？现在的这个只考虑了springboot ,所以少了一个contextPath，已经提交修复了这个问题，具体修改可见：https://github.com/caspar-chen/swagger-ui-layer/commit/90006df9ad3f66a1452a46e9d305ef5abd0e167a
