### ISSUE TITLE
返回对象里嵌套对象不能显示完全

### ISSUE THREAD

**Issue by youz88** [caspar-chen/swagger-ui-layer#13]
比如返回json对象
`{"code":200,"msg":"消息","data":{"id":1,"userName":"admin"}}`
显示出来的效果为

Properties | Type | Description
---- | ------ | ----
code  |  integer | 描述
data | object | 描述
msg | string | 描述

**Comment by caspar-chen** [comment]
可以是用@ApiOperation注解的response参数来指定文档返回的类型，
例如返回User类： @ApiOperation(response = User.class)
User 类里面的属性用@ApiModelProperty注解
@ApiModelProperty("姓名")
private String name;

**Comment by youz88** [comment]
主要是嵌套对象的问题，我全局统一返回的是一个Result对象，这个对象里包含code、msg、真正返回的实体对象T。我希望能实现这种效果（以下是同样的代码）

springfox-swagger-ui
![1](https://user-images.githubusercontent.com/25759289/39848369-285b89b2-5439-11e8-987e-88fd5b4b5c79.png)
swagger-ui-layer
![2](https://user-images.githubusercontent.com/25759289/39848377-366d17a0-5439-11e8-8f51-9769857aa13e.png)

**Comment by dada0901** [comment]
@youz88 我也遇到类似的问题，请问最后怎样解决的？

**Comment by caspar-chen** [comment]
感谢反馈，0.0.5 版本已经解决了这个问题，可以显示任意层嵌套对象的属性

**Comment by mengxuef** [comment]
今天刚刚也遇到这个问题，google到这里 ，直接就解决了，swagger 太强大了

**Comment by ronghuaxueleng** [comment]
这个是怎么解决的？

**Comment by hzwjs** [comment]
如何 解决了的？

**Comment by zhourui9797** [comment]
如何解决的

**Comment by caspar-chen** [comment]
用新版本就可以了： 1.1.3
