### ISSUE TITLE
能否在调试页面允许填写Header字段信息

### ISSUE THREAD

**Issue by frontc** [caspar-chen/swagger-ui-layer#19]
如题。token通常在头部的Authrazation里。调试页面允许填这个就会好很多。
PS：谢谢作者的工作。的确比swagger-ui好看很多。

**Comment by caspar-chen** [comment]
如果接口中定义了header参数的话，调试页面会显示，[kaifahm](https://github.com/caspar-chen/swagger-ui-layer/pull/18) 之前已经加入了header参数，正式版本还未上传到maven库
