### ISSUE TITLE
docs.html页面结构有问题debug不能使用

### ISSUE THREAD

**Issue by cokestewpotato** [caspar-chen/swagger-ui-layer#25]
主要是少了两个dev加ayui-tab-item嵌套导致的，附上源码有点乱，给取消了，大家可以自己手动改下

**Comment by caspar-chen** [comment]
希望直接commit你的代码，如果没问题的话，我会merger的

**Comment by cokestewpotato** [comment]
那我研究下怎么commit，刚试了下下载的项目没关联上Git

**Comment by cokestewpotato** [comment]
你试试可以看到我的提交吗

**Comment by caspar-chen** [comment]
在你fork的仓库下面点击 “New Pull Request”

**Comment by caspar-chen** [comment]
感谢贡献你的代码，已经merger了

**Comment by cokestewpotato** [comment]
这样我就不用手动上传jar到我们的服务器，谢谢你的开源

**Comment by cokestewpotato** [comment]
为什么我下下来的包还是不对的，是maven库没有更新吗？

**Comment by caspar-chen** [comment]
是的，maven库还没更新，刚刚发布了0.0.6版本，可能要等2个小时就可以了
