### ISSUE TITLE
required必填项没有校验

### ISSUE THREAD

**Issue by bill1314** [caspar-chen/swagger-ui-layer#28]
作者辛苦了，required必填项没有校验

**Comment by caspar-chen** [comment]
谢谢反馈，这个校验，原先设计的时候是没打算加的，因为需要测试前端不传必填参数的时候，后端返回情况。是否做了正确的异常处理等。
关于这个问题也可讨论是否有必要加。

**Comment by caspar-chen** [comment]
经过考虑，不进行必填校验
