### ISSUE TITLE
注释没有显示，Responses 返回对象里面有包含其它对象实体，实体的注释没办法显示

### ISSUE THREAD

**Issue by bill1314** [caspar-chen/swagger-ui-layer#29]
例如下代码，data是一个实体类，实体的注释无法显示了

@ApiModel("返回响应数据ResponseResult")
public class ResponseResult<T> {

  @ApiModelProperty("错误码,1成功 0失败")
  private int code;
  @ApiModelProperty("执行结果描述")
  private String desc;
  @ApiModelProperty("版本")
  private String version;
  @ApiModelProperty("数据")
  private T data;

**Comment by caspar-chen** [comment]
1.0.0 正式版已经修复了该问题，可以更新到1.0.0版本
