### ISSUE TITLE
当返回值为String的时候，debug没有结果显示

### ISSUE THREAD

**Issue by qingmg** [caspar-chen/swagger-ui-layer#32]
如图，谷歌浏览器调试模式中 Network 可以看到请求已经发出，且返回结果正常，但页面无反应。
用的 @RestController，所以无需 @ResponseBody。
![image](https://user-images.githubusercontent.com/18192124/45070050-17ac0300-b102-11e8-8027-b5515cf7f52f.png)
![image](https://user-images.githubusercontent.com/18192124/45070067-2e525a00-b102-11e8-9973-90dda7dbd5ee.png)
![image](https://user-images.githubusercontent.com/18192124/45070186-ae78bf80-b102-11e8-8a22-ef69800ec210.png)

**Comment by caspar-chen** [comment]
最新版1.1.1 是可以直接显示string的了
