### ISSUE TITLE
接口测试时，query string 参数会 拼接两次

### ISSUE THREAD

**Issue by ywyuanyz** [caspar-chen/swagger-ui-layer#38]
form 提交请求参数时，Request URL 中会将参数拼接两次
如提交请求参数：
module=asd

则 Request URL为：
http://suldemo.tianox.com/banner?module=asd&module=asd

**Comment by caspar-chen** [comment]
谢谢反馈，下一次发版的时候会修复这个问题，连同其他的改进一起发版

**Comment by caspar-chen** [comment]
新版本已经修复
