### ISSUE TITLE
1.1.3版本与原生swagger-ui对比后发现的一些不足

### ISSUE THREAD

**Issue by wwjjkk** [caspar-chen/swagger-ui-layer#51]
本想打算用这个ui替换原生ui结果发现跟原生ui相比虽然整体上要好看一些，但同样存在不少地方反而比不上原生ui，最终暂时放弃对原生的替换。
主要问题如下：
1、@ApiModelProperty设置example参数无效，无法提供默认查询示例
2、debug中json参数只能自行输入，而原生ui只需要点击默认示例即可
3、原生ui在每次点击对应接口后url会发生变化，而swagger-ui-layer所有接口显示的url都一样，导致刷新页面后需要重新查找之前的接口
以上问题导致再开发和测试时使用反而不如原生ui好用，建议以后改进

另外建议添加对接口排序的支持。

**Comment by caspar-chen** [comment]
感谢您反馈的真实体验
1、example参数现在确实没有体现，之后会加上
2、参数的填充，后期准备实现mock的功能
3、现在的网页内容都是js请求的，所以url都一样，后续可以通过锚点或其他形式来实现
4、排序问题：因为swagger的position参数无效了，生成的json文件没有排序字段，所以没办法自定义排序，现在是默认按path名字排序的。
（如果后续自定义的需求较多但受限与swagger的话，可以考虑改进swagger注解，新增一些参数）

**Comment by wwjjkk** [comment]
ApiOperation的position被废弃后接口排序默认确实只能按url排序。
我说一下目前项目中的采用的处理方式以供参考。修改springfox-swagger-ui的springfox.js
window.swaggerUi = new SwaggerUi({  
...  
apisSorter: "alpha", 
operationsSorter : "method" 
});  
后可支持按@ApiOperation的notes排序（开头用数字编号）

期待后续版本的完善，持续关注中
